sudo: required
dist: trusty

language: java
jdk:
- oraclejdk8

cache:
  directories:
  - $HOME/.m2/repository

before_install:
  # allocate commits to CI, not the owner of the deploy key
  - git config user.name "opentracingci"
  - git config user.email "opentracingci+opentracing@googlegroups.com"

  # setup https authentication credentials, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials

branches:
  except:
    - /^[0-9]/

jobs:
  include:
    - stage: test Vert.x 3.3.0, 3.4.0, 3.5.0.Beta1
      script: ./mvnw clean test -Dversion.io.vertx=3.3.0
    - script: ./mvnw clean test -Dversion.io.vertx=3.4.0
    - script: ./mvnw clean test -Dversion.io.vertx=3.5.0.Beta1
    - stage: deploy
      script: ./travis/publish.sh

env:
  global:
  # Ex. travis encrypt -r org/repo GH_TOKEN=XXX-https://github.com/settings/tokens-XXX
  - secure: "SzVTeGKKU3PEe1Yc1jQjlFQViRv/IqWOVtPD/MINOxiGERyIxYNsEQ2zEEjW/zzJdUIrQU3uLBZL6+91lAhiBE4s5mjmfMrLyWxlHsd3XxgC3lFek5zloMgyqmk0Po35CCHY6cH4thecwVE1xt71apOzdRAbSHb5/gxdo0vAl5sU/lxa6YQ8I+Ag5BDNrXeH9Wrxs0kgRGyKRFamdjbT1Q2FcrDCnhN2oUwwKGNDStZeGRb847GiMisY3XhNYqfWoQ69qoDgW6PbcqUxndxHJcvaIPQCFY6GAuFNd8kM2Nzll0F+YmHf8mEYkimqdLTc0qXvXxyx+1UXd/aWbnjRURfIg0LvOf3NutGOvxYovqNG5OzDEWKESHQx2i3ZOo/a4ZpouT5GJUeSkFXyxsr/yGMR8LfSzB5jAdBBumyMBTLlDSxpXVoWvNoukga1DdmVcj/lD/eLxuiLjkwzIFloVvMDa//4PlCeb9Y2B7Fthw3T/+Er5b2sRX1hP5wBCiuI9SfOJaS8oydScpeKpEOeg/XdJmRc1/bjaduoaOIEsAeXuVlWWG/LWHHbEfnaEWL7GaKyknxQID34cBSUYIT4ZyNxV8PHDNAOkS/L/V/bEU271njCfRWGAXINzvIqK/LqsaWVhLunc86LCGJa9OCHayGQ5uVeFQdgLTF9GnaUYXQ="
  # Ex. travis encrypt -r org/repo SONATYPE_USER=your_sonatype_account
  - secure: "X1dg+ITMFNjqx3m43SEmcXEbtpkUrTvBM2XbhBR9N2+/3WShUxP58+uzDVSnCelQ2OvGnHZBaJjnbPjlvOdzWRHsuSsARnIiiGDYDgJ/UlnRycw0OsexEFmIFfR8v+tS6KPuDvUauI7759MzVh28iDYsGhhRN0Y/K24ceyWV5UaSGKNuoKNlKrKM+nUNY4hST1/vZ3SGLzY6IQJdqaFXlkhbTx6bcfG+Nct/p2RQ9UUXgfkg2ImzmLcseWCG+dilPlVopQBX3IldNfQtUDFPSP9VVZt8D7ihXMAPfGgslpuyW9ZTAyRWxAlCDO1YDnoV3M+Vw183I/GIbE60eN8sfs/0A1yinLaqu33FDQqR9uKh4rDUOSM4jCJBkNcDsp8aopx/cPRnQP6sdw6bHQ3jYok7sz0n9jDUk8dQPt4dqg5b/H9hMSZZ+ZNpFksSzcSO3iispTOBTXt9TJgAhqxbIN7Wu4oxDQnCN4QW2+JJOB0+B4ryICohVym64OqMbCmJxKr3ZcV4HYVb5kA4y7RC2z7Ax/dbwX5i0t/MnwDzkus5c3BRC8bWbMNH6wjrxbIhhjzr1L4pKphdZRFdnzu7JGJcrysRQhWmkyLeKqaYPnsa9hCkh38enGrT5k9jxJAxTuCRpAt2qzsGxhDMp4vHdU+2+phkkVWiJo6O85iPDRA="
  # Ex. travis encrypt -r org/repo SONATYPE_PASSWORD=your_sonatype_password
  - secure: "to0QA++NLPF8CtENkQq9YylvHqDYjW5qU3lERrxjvFtXJVebrgxMXS2tjh5BDqfgC4QCNLykOPrmOTKtn020UP5psRuzlXeZIR7HlEEn9AqnCSGu+GdVisRZmoh4jz57DVt+xhsxRl2NmK66W0Q+5zfrHOrnLrfw5vv8T3xW9/PEgxBM+bAdIFvNkQxd0+EloY/l+7DUwJXpzp6YTOOrNANjV0mRgEW7PYns60vmzSoFhI5MgAP/+qihzBtULmVYhcQ0NTk6VNcNV0soU1PqSmrg3uHUQk3vvTIYwVosy1i9ZYPIYpvRutc6/NVGzFwwWVicnGhGgoJxAuxemHE/N3eoHzFZDd+aLRQlwhpLP2i11EzA8fR5tagKgbDQf/wcK0xeG4caXdjeEDgL0tLgEpSrBGk7Wm2+gs8ll6bny9oLnXF28bFG4JbGfpByf40Qo5Quaqx+tLW2/MBcMVbjpXapKdRu7j1L7hdg1cUinpmgd1j923szG/7h9LZCm5EN1v5bE0Ov7eN5flRJ0cGlq9ZvtcS1+FEPBH33zYRPpc9WmOR5rrhEB1gHrw1o64uaiF+DpYkHAXrSg95BhMl4K3PD0KZ998KzFw+RL8g0ORymSqdhBmsejt12ymlvzdfydwa4F00L50xFLSWrkJmBz9kpuOurGyi+vb0fWCDeceQ="
  # Ex. travis encrypt -r org/repo BINTRAY_USER=your_github_account
  - secure: "nhuLgpJXQUroDEBVIAoxBZxMzEyk/NC+oeA/9RfspKhnBzMDan0I6ghlgBy//T86sR1Np6+9sLp7ncqvB1BIszscgFxCj+vaOvIpT71VpVeqXsfB5X18L6ZhENN0LFmLQd2B6Tc5nZuVV+wdDONuuIMa1l0ZEWzNrjBzHkFqsaPKY2blKNThRYVk6IIvCSlfb1DKPJ43Atoyb2ayIGaCsVjMCCRP3+n+YMS7WnozcYoNBEfMGdzxr2MsZfYxYyJt8lyOz27ORInlIWQrWkno6BCtbaRW01OB7MpqMZR0WzzYNyzHdmmjjH2QP+EpGuFF7O16XJrm/MxCZ+oJtFZJeVtTfY1WJYj7XSpwPJ312NDXh7nzH5pq9f0gFQkQi51rdAJxhML//UVOZWQK6/51AYYRMnqwFxva5m+W+QCjzvf4fgUwRLNWa1IwkqJ888Y2qdt+q3GPgDYn6788uNH6qFXPkZXs0guYXzteav1lXRWzjmyXcLeD2/SHSe4ANDP50jNiYFvvf0meUdT1eAZjqiQ1u5cQQa5ahE1MQOebxz/805RVua699smGzGQoOOx7V6a5v88YMeXSUu1ltHjSWjtbSnq3t5EgotmZuQX6Wb+TFIlIt2RBUh+jUZtLMDXTfLdzqPfEFSAQoAf8wFrPjRD9dOnHaXM8SLCavr/uKw8="
  # Ex. travis encrypt -r org/repo BINTRAY_KEY=xxx-https://bintray.com/profile/edit-xxx
  - secure: "NQvVVvWbctpcpsyRTJtXjPA40FA8YhK6xKpuAhx+H8qdCKAtSkuIbqYyRQoMXxqC9cYLkplNNsPylPy4JSEPqaf8M6e7OhcFy5NlFmpwnQ+Ubwex6ojK8PGszFsCWtoxjjgenS6AC3zhwuOYRYSWuEw2r8DbDaFwqeFC0nKULUw2UjVD21IVuG2mAH+W3B9ktDEUoDWIxBSHo7pwTwb2qU91GDQDMUiwA4vd4rf7wVET5njua8L8OYbE5z81BHizg2HTD9Or7K0Bm6uXzJqxUMIE4XrBYQ5N7YfTSTJJRS2Btbo7kWDKnCeefc22nWW8U3nuJ3EpKauaWHKRaNng73ai6Vz2CH2TQ0MNeMZgLQoeHdNv9MFVT0JupYdOku19SQQ6uPD2mjMIBHQ5Gf96EYWNfdUOkDH90iiQsqP7BPUPAk4H13SIjCb3eVaPezpzlpT+kVIw7KW4iB0o7/JDuBaBNteq1f5qGXcVF+6/YZBT8yVXEMWv4H+lP/E9QiHE81J42j5cIrZCvpfPHpDf0smCjVTWGGjm5zve/R3RKGruzPHpDl6dwapyuGCdpg42qN90LrsOb08QLRmp5ujHg9tI70ApDl3VZGaVaIqRqkYCogvtqQTDBToCIB7Cz0NY25nc9/uYoKmGpa+6KSR4RGp6KCmk8Sowpkzaq2q+C0k="
